import logging

print(logging.error("error"))